// AUTOGENERATED - MANUAL CHANGES WILL BE REVERTED BY THE GENERATOR
// SPDX-License-Identifier: MIT
pragma solidity >=0.6.0;

import {IPoolAddressesProvider, IPool, IPoolConfigurator, IAaveOracle, IPoolDataProvider, IACLManager, ICollector} from './AaveV3.sol';
library AaveV3Monad {
  // https://monadscan.com/address/0x34793Fb9935F7bB5E5aE920fb963F39063E7A615
  IPoolAddressesProvider internal constant POOL_ADDRESSES_PROVIDER =
    IPoolAddressesProvider(0x34793Fb9935F7bB5E5aE920fb963F39063E7A615);

  // https://monadscan.com/address/0x69a5F9AD4f96ebf0a0C792dD42a01cC5C0102fef
  IPool internal constant POOL = IPool(0x69a5F9AD4f96ebf0a0C792dD42a01cC5C0102fef);

  // https://monadscan.com/address/0xC7A386Da9cB528aa86feD862a7bf33d10AA8455B
  IPoolConfigurator internal constant POOL_CONFIGURATOR =
    IPoolConfigurator(0xC7A386Da9cB528aa86feD862a7bf33d10AA8455B);

  // https://monadscan.com/address/0x0c02b2c2038066C10Eab8fe1D5Cdb73d5a78A1Bf
  IAaveOracle internal constant ORACLE = IAaveOracle(0x0c02b2c2038066C10Eab8fe1D5Cdb73d5a78A1Bf);

  // https://monadscan.com/address/0xa9d0EAFF48cE1DF468f9eAeb7e628c413343F6A2
  address internal constant ACL_ADMIN = 0xa9d0EAFF48cE1DF468f9eAeb7e628c413343F6A2;

  // https://monadscan.com/address/0xa9fEe192a76B8f5e5f3d310AB6C526cB11F3d95B
  IACLManager internal constant ACL_MANAGER =
    IACLManager(0xa9fEe192a76B8f5e5f3d310AB6C526cB11F3d95B);

  // https://monadscan.com/address/0xB65A68B98274ef7D9a60E0C0747dD1BEc3D32fad
  IPoolDataProvider internal constant AAVE_PROTOCOL_DATA_PROVIDER =
    IPoolDataProvider(0xB65A68B98274ef7D9a60E0C0747dD1BEc3D32fad);

  // https://monadscan.com/address/0x9539531EA4f6563A66421a7449506152609985be
  address internal constant POOL_IMPL = 0x9539531EA4f6563A66421a7449506152609985be;

  // https://monadscan.com/address/0xCCFCA00657f9c7e062E0512c8535a5B93D5Ff254
  address internal constant POOL_CONFIGURATOR_IMPL = 0xCCFCA00657f9c7e062E0512c8535a5B93D5Ff254;

  // https://monadscan.com/address/0x6f275486dC3EF07691B846E500556774B2D98F59
  address internal constant DEFAULT_INCENTIVES_CONTROLLER =
    0x6f275486dC3EF07691B846E500556774B2D98F59;

  // https://monadscan.com/address/0x2da993D6c83408039b6842Aa56A9dE8044Dc7311
  address internal constant EMISSION_MANAGER = 0x2da993D6c83408039b6842Aa56A9dE8044Dc7311;

  // https://monadscan.com/address/0x22A14267f9F8bA21D11898F0772e652B09e6A8A1
  ICollector internal constant COLLECTOR = ICollector(0x22A14267f9F8bA21D11898F0772e652B09e6A8A1);

  // https://monadscan.com/address/0xdB1E821a05E6028c6CD440FFE94F6bfCb3B3028d
  address internal constant DEFAULT_A_TOKEN_IMPL = 0xdB1E821a05E6028c6CD440FFE94F6bfCb3B3028d;

  // https://monadscan.com/address/0xCCDA7A6386fb2fBE4B22a5485A599F6d68d95d78
  address internal constant DEFAULT_VARIABLE_DEBT_TOKEN_IMPL =
    0xCCDA7A6386fb2fBE4B22a5485A599F6d68d95d78;

  // https://monadscan.com/address/0x25cA98Ab620Af65E8A9FB0F30989b9FFfb8e3163
  address internal constant CONFIG_ENGINE = 0x25cA98Ab620Af65E8A9FB0F30989b9FFfb8e3163;

  // https://monadscan.com/address/0x98217A06721Ebf727f2C8d9aD7718ec28b7aAe34
  address internal constant RISK_STEWARD = 0x98217A06721Ebf727f2C8d9aD7718ec28b7aAe34;

  // https://monadscan.com/address/0x1c930A46f01542882Fb43031DeD31f06C8cF278d
  address internal constant RISK_COUNCIL = 0x1c930A46f01542882Fb43031DeD31f06C8cF278d;

  // https://monadscan.com/address/0xa7790F5EDE1f1A57e7122e869eF6095c07C7E01d
  address internal constant POOL_ADDRESSES_PROVIDER_REGISTRY =
    0xa7790F5EDE1f1A57e7122e869eF6095c07C7E01d;

  // https://monadscan.com/address/0xa7D38785be3422c25677A8aa4a44D3a0853A3a17
  address internal constant UI_POOL_DATA_PROVIDER = 0xa7D38785be3422c25677A8aa4a44D3a0853A3a17;

  // https://monadscan.com/address/0x9d8678556BCF7240bE12982430C281Db76E26eA2
  address internal constant UI_INCENTIVE_DATA_PROVIDER = 0x9d8678556BCF7240bE12982430C281Db76E26eA2;

  // https://monadscan.com/address/0x1CC19583933Af0B70103797236267a9E049806F9
  address internal constant WALLET_BALANCE_PROVIDER = 0x1CC19583933Af0B70103797236267a9E049806F9;

  // https://monadscan.com/address/0x5bB847f1E529df8819038BA6d34a95c9C2FB6813
  address internal constant WETH_GATEWAY = 0x5bB847f1E529df8819038BA6d34a95c9C2FB6813;

  // https://monadscan.com/address/0x9ce311E3Ea6e781DC9a3a7F61ef24250E2B8cDF8
  address internal constant STATA_FACTORY = 0x9ce311E3Ea6e781DC9a3a7F61ef24250E2B8cDF8;

  // https://monadscan.com/address/0xf23C65c8C92E42e990786523744Db9d5cdcF6cbE
  address internal constant DUST_BIN = 0xf23C65c8C92E42e990786523744Db9d5cdcF6cbE;
}
library AaveV3MonadAssets {
  // https://monadscan.com/address/0xe7cd86e13AC4309349F30B3435a9d337750fC82D
  address internal constant USDT0_UNDERLYING = 0xe7cd86e13AC4309349F30B3435a9d337750fC82D;

  uint8 internal constant USDT0_DECIMALS = 6;

  // https://monadscan.com/address/0x3c187a25f0f05E009DA794069682653e40062730
  address internal constant USDT0_ORACLE = 0x3c187a25f0f05E009DA794069682653e40062730;

  // https://monadscan.com/address/0x1f6F08BC1Da8B311bf6D87b829AD2FFAA8fB8211
  address internal constant USDT0_INTEREST_RATE_STRATEGY =
    0x1f6F08BC1Da8B311bf6D87b829AD2FFAA8fB8211;

  // https://monadscan.com/address/0x754704Bc059F8C67012fEd69BC8A327a5aafb603
  address internal constant USDC_UNDERLYING = 0x754704Bc059F8C67012fEd69BC8A327a5aafb603;

  uint8 internal constant USDC_DECIMALS = 6;

  // https://monadscan.com/address/0x787962943811D279d01eC973Bd3A15f1b3e1F0D9
  address internal constant USDC_ORACLE = 0x787962943811D279d01eC973Bd3A15f1b3e1F0D9;

  // https://monadscan.com/address/0x1f6F08BC1Da8B311bf6D87b829AD2FFAA8fB8211
  address internal constant USDC_INTEREST_RATE_STRATEGY =
    0x1f6F08BC1Da8B311bf6D87b829AD2FFAA8fB8211;

}
library AaveV3MonadEModes {
  uint8 internal constant NONE = 0;

  uint8 internal constant syrupUSDC__USDT0_USDC_mUSD_AUSD_GHO = 1;

  uint8 internal constant USDe_sUSDe__USDT0_USDC_AUSD_GHO = 2;

  uint8 internal constant wstETH__WETH = 3;

  uint8 internal constant weETH__WETH = 4;

  uint8 internal constant PT_AUSD_8OCT2026__USDT0_USDC_USDe_GHO = 5;
}
library AaveV3MonadExternalLibraries {
  // https://monadscan.com/address/0x6D414cd0d5eAf8C43200ac0c325A7E2Ad83B8be6
  address internal constant FLASHLOAN_LOGIC = 0x6D414cd0d5eAf8C43200ac0c325A7E2Ad83B8be6;

  // https://monadscan.com/address/0x52Da0ce88202D1542543598D1e1e27F0d344726A
  address internal constant BORROW_LOGIC = 0x52Da0ce88202D1542543598D1e1e27F0d344726A;

  // https://monadscan.com/address/0x96D5686812e33Ab509ECCDb38C89d15607B2a413
  address internal constant LIQUIDATION_LOGIC = 0x96D5686812e33Ab509ECCDb38C89d15607B2a413;

  // https://monadscan.com/address/0xD70593841C57cbaA04957cc3EAcE95708e48853b
  address internal constant POOL_LOGIC = 0xD70593841C57cbaA04957cc3EAcE95708e48853b;

  // https://monadscan.com/address/0x584C7d8c4cb05304FE5Ac7fbc97f20A10Fb07564
  address internal constant SUPPLY_LOGIC = 0x584C7d8c4cb05304FE5Ac7fbc97f20A10Fb07564;
}
